Fix integration test failure which occurs with changes in #8
(Sorry these integration tests are currently setup to run only on my pc.
#8 introduced a next exception failure when trying to scan games that don't
exist on the local pc.

Before this fix:

Warning: no info found for 555 - simulating...
INFO:root:Attempting backup of {'install_root': '/home/kevinh/.steam/debian-installation', 'game_id': 555, 'game_name': None}
DEBUG:root:No rcf /home/kevinh/.steam/debian-installation/userdata/49847735/555/remotecache.vdf
DEBUG:root:No rcf /home/kevinh/.steam/debian-installation/userdata/49847735/555/remotecache.vdf
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kevinh/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/kevinh/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/kevinh/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/home/kevinh/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kevinh/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__main__.py", line 85, in <module>
    main()
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__main__.py", line 76, in main
    asyncio.run(test.testImpl(e))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/test.py", line 76, in testImpl
    si = await p.do_backup(make_game_info(p, 555))
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 579, in do_backup
    rcf = self._read_rcf(game_info)
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 405, in _read_rcf
    saveRoot = self._find_save_games(game_info, rcf)
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 322, in _find_save_games
    d = self._search_likely_locations(game_info, rcf)
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 294, in _search_likely_locations
    addRoots(False)
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 278, in addRoots
    roots.append(self._get_game_saves_root(
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 200, in _get_game_saves_root
    installdir = self._parse_installdir(game_info)
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 149, in _parse_installdir
    vcf = _parse_vcf(os.path.join(
  File "/home/kevinh/development/steamdeck/Steamback/py_modules/steamback/__init__.py", line 25, in _parse_vcf
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kevinh/.steam/debian-installation/steamapps/appmanifest_555.acf'
kevinh@kdesktop:~/development/steamdeck/Steamback$  cd /home/kevinh/development/steamdeck/Steamback ; /usr/bin/env /usr/bin/python3