fix this logspam for non-mounted games
[2024-03-01 10:43:02,394][ERROR]: Failed parsing vcf /run/media/mmcblk0p1/steamapps/appmanifest_2080690.acf due to exception Traceback (most recent call last):
  File "/home/deck/homebrew/plugins/steamback/py_modules/steamback/__init__.py", line 27, in _parse_vcf
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/mmcblk0p1/steamapps/appmanifest_2080690.acf'
...